name: publish-dev
on: 
  push:
    branches:
      - 'develop'

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm test
      - name: Coveralls
        uses: coverallsapp/github-action@v2
  

      - name: Build the hello-docker Docker image
        run: |
          docker build . --tag ghcr.io/jo15122002/hello-docker-gcr-demo:staging
          docker push ghcr.io/jo15122002/hello-docker-gcr-demo:staging